### ISSUE TITLE
Duplication of effort

### ISSUE THREAD

**Issue by thisfred** [mikeckennedy/python-switch#2]
Far be it from me to tell you how to spend your time ;), but a cursory search revealed a 4 year old project that does almost exactly the same thing: https://pypi.python.org/pypi/switch/1.1.0 Did you try contacting the author to see if you could contribute to that, or take over maintainership?

**Comment by thisfred** [comment]
(If you did know about this project, and decided you wanted a different approach, which is a totally reasonable option, I would mention it in the README as an inspiration at least, and describe how your design decisions differ and why.)

**Comment by mikeckennedy** [comment]
Hi @thisfred , thanks for the link. 

I originally posted this just to see what the reaction to the whole idea was. I've since gotten a lot of links such as this to other areas people are playing with. However, I do respect what they were after but I honestly don't see why I would use https://pypi.python.org/pypi/switch/1.1.0 rather than just an if statement sequence and a loop. It seems SO verbose.

Here's some code for a command loop in an app I'm writing now for a course I'm working on. If we can get a nice clean option like this then I'll consider my take duplicate. :)

```python
while True:
    action = get_action(action)

    with switch(action) as s:
        s.case(['c', 'a'], create_account)
        s.case('l', log_into_account)
        s.case('r', register_cage)
        s.case('u', update_availability)
        s.case(['v', 'b'], view_bookings)
        s.case('x', exit_app)
        s.case('', lambda: None)
        s.default(unknown_command)
```

**Comment by mikeckennedy** [comment]
Just thinking through how it would look in their case, seems super verbose:

```python
while True:
    action = get_action(action)

    with CSwitch(val) as case:
            if case('c'):
                create_account()

            if case('a'):
                create_account()

            if case('l'):
                log_into_account()

            if case('r'):
                register_cage()

            if case('u'):
                update_availability()

            if case('v'):
                view_bookings()

            if case('b'):
                view_bookings()

            if case('x'):
                exit_app()

            if case.default:
                unknown_command()
```

**Comment by thisfred** [comment]
Yep, I agree your syntax is nicer. :)
